openapi: 3.0.0
servers: []
info:
  description: Managed attributes schema
  version: "1.0.0"
  title: Managed attributes schema
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /v1/managed-attribute:
    get:
      summary: get one managed attribute
      operationId: getManagedAttribute
      description: |
        By passing in the id, user can get available managed attributes authorised to the user
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: true
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: managed attributes with the given id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManagedAttribute'
        '400':
          description: bad input parameter
    post:
      summary: adds a managed attribute  item
      operationId: addManagedAttribute
      description: Adds a managed attribute
      responses:
        '201':
          description: managed attribute created
        '400':
          description: 'invalid input, object invalid'
        '409':
          description: an existing managed attribute already exists
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManagedAttribute'
        description: Managed attribute to add
components:
  schemas:
    ManagedAttribute:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              example: d290f1ee-6c54-4b01-90e6-d701748f0851
            type:
              type: string
            attributes:
              type: object
              required:
                - name
                - managedAttributeType
              properties:
                name:
                  type: string
                  description: ref to the name of the managed attribute
                  example: 
                    - specimen_view
                    - identifier
                    - identifier_scope
                    - type_status
                managedAttributeType:
                  type: object
                  description: ref to the type of the managed attribute                  
                  example: 
                    - specimen_view
                    - identifier
                    - identifier_scope
                    - type_status
                acceptedValues:
                  type: array
                  description: ref to the accepted values of the named attribute if any      
                  items: 
                    type: string                  
                  example:
                    - dosal for specimen_view
                createdDate:
                  type: object							      
                  description: initial date this managed attribute was created if any      
                description:
                  type: string
                  description: description of this managed attribute in both language if any                      

                
                    
                  
                
                           
