openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Object Store API Schema
  version: "0.1.0"
  title: Object Store API Schema - DRAFT
  contact:
    email: dina-aafc@canada.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/metadata:
    $ref: 'metadata.yaml#/paths/~1v1~1metadata'
  /v1/metadata/{Id}:
    $ref: 'metadata.yaml#/paths/~1v1~1metadata~1{Id}'  
  /v1/managed-attribute:
    $ref: 'managedAttribute.yaml#/paths/~1v1~1managed-attribute'    
  /v1/managed-attribute/{Id}:
    $ref: 'managedAttribute.yaml#/paths/~1v1~1managed-attribute~1{Id}'
  /v1/object-subtype:
    $ref: 'objectSubtype.yaml#/paths/~1v1~1object-subtype'
  /v1/object-subtype/{Id}:
    $ref: 'objectSubtype.yaml#/paths/~1v1~1object-subtype~1{Id}'
