openapi: 3.0.0
servers:
  - description: DINA - AAFC
    url: https://virtserver.dina-aafc.com/AAFC/1.0.0
info:
  description: Object Store API Schema
  version: "0.1.0"
  title: Object Store API Schema - DRAFT
  contact:
    email: info@dina-project.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
   
paths:
  /v1/metadata:
    $ref: 'metadata.yml#/paths/~1v1~1metadata'
  /v1/metadata/{Id}:
    $ref: 'metadata.yml#/paths/~1v1~1metadata~1{Id}'  
  /v1/managed-attribute:
    $ref: 'managed-attribute.yml#/paths/~1v1~1managed-attribute'    
  /v1/managed-attribute/{Id}:
    $ref: 'managed-attribute.yml#/paths/~1v1~1managed-attribute~1{Id}'
  /v1/object-subtype:
    $ref: 'object-subtype.yml#/paths/~1v1~1object-subtype'
  /v1/object-subtype/{Id}:
    $ref: 'object-subtype.yml#/paths/~1v1~1object-subtype~1{Id}'
  /v1/derivative:
    $ref: 'derivative.yml#/paths/~1v1~1derivative'
  /v1/derivative/{Id}:
    $ref: 'derivative.yml#/paths/~1v1~1derivative~1{Id}'
  /v1/file/{bucket}:
    $ref: 'file.yml#/paths/~1v1~1file~1{bucket}'
  /v1/file/{bucket}/derivative:
    $ref: 'file.yml#/paths/~1v1~1file~1{bucket}~1derivative'
  /v1/file/{bucket}/{fileId}:
    $ref: 'file.yml#/paths/~1v1~1file~1{bucket}~1{fileId}'
  /v1/file/{bucket}/derivative/{fileId}:
    $ref: 'file.yml#/paths/~1v1~1file~1{bucket}~1derivative~1{fileId}'
